homework 1 - logger
Oleksander-Hnatiuk/nodejs_hw_Hnatiuk_Oleksander pull request #1
Opened 2024-12-08 12:56 UTC by Oleksander-Hnatiuk

2024-12-08 17:53 UTC, virtax requested changes

2024-12-08 17:53 UTC, virtax commented on utils/logger.js
> +});
Додайте ще, будь ласка, warn з console.error та перемістить весь код у нову підпапку у корні 'homework_01' (бо ще будуть наступні окремі "homework_02" і т.д.)

2024-12-08 20:00 UTC, Oleksander-Hnatiuk commented on utils/logger.js
> +});
done

2024-12-09 15:22 UTC, virtax approved these changes

2024-12-09 15:22 UTC, merged